apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-informer
spec:
  replicas: 2
  template:
    metadata:
      name: system-informer
    spec:
      containers:
        - image: 'ghcr.io/gitops-poc/system-informer@sha256:55c6cb6317c1a71cc256d08781e8c2e3e0eeb06b66af331d87a8c7fc37929203'
          name: systeminformer
