apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-informer
spec:
  replicas: 2
  template:
    metadata:
      name: system-informer
    spec:
      containers:
        - image: 'ghcr.io/gitops-poc/system-informer@sha256:5632d0525b06fa1bfc6b10010fd8c415d9d60031d38bbcd14379e50a1d629f68'
          name: systeminformer
